### ISSUE TITLE
You should use GitHub actions and not Travis&Co ;)

### ISSUE THREAD

**Issue by lrnv** [BereniceAlexiaJocteur/CausalForest.jl#1]
As the title say. Consider re-running PkgTemplate with github actions CI instead, it will save you troubles later (GA is a lot easier to use and manage than the rest).

Cheers ;)

**Comment by BereniceAlexiaJocteur** [comment]
Hey, thank you for your comment !

So I should use GA instead of travis CI and still use codecov ? And indeed the trigger for Documenter.jl on GA instead of Travis seems simpler to implement.

Cya

**Comment by lrnv** [comment]
Yep, that's the general advice these days -- Travis is slowly dying in favor of Github action.
